### Create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "haitn.1@gmail.com",
  "password": "bnksolution"
}

### Find a particular user with a given id
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=haitn.1@gmail.com

### Remove a particular user with a given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "haitn.2@gmail.com",
}